apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: xkcle280f-nodejs-gitops
  description: This is GitOps manifest for xkcle280f-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=xkcle280f-nodejs
    backstage.io/kubernetes-id: xkcle280f-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: xkcle280f-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:xkcle280f-nodejs
