apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xkcle280f-nodejs
  janus-idp.io/tekton: xkcle280f-nodejs
  backstage.io/kubernetes-id: xkcle280f-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xkcle280f-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
